# Generated by Django 3.1.3 on 2020-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_shop', '0003_auto_20201110_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedescription',
            name='additional_photo',
            field=models.ImageField(upload_to='movie/%Y/%m/%d', verbose_name='Дополнительное'),
        ),
        migrations.AlterField(
            model_name='moviedescription',
            name='poster',
            field=models.ImageField(upload_to='movie/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='moviedescription',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='moviedescription',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='moviedescription',
            name='treiler',
            field=models.URLField(verbose_name='Треилер'),
        ),
    ]
